Repository GiganticMinecraft/SeichiAssist, pull requests merged in 2025-06, with the labels that each got.

#2567 リリースノートを自動で作成させる
  .github/release.yml
  .github/workflows/auto-attach-label.yaml
  .github/workflows/check-pr-labels.yml
  CONTRIBUTING.md
Labels: development

#2570 fix: release.yml の exclude label の指定形式を直す
  .github/release.yml
Labels: Build / CI

#2571 ci: リリースを作成するときに、GitHub が作成したリリースノートを持ってくるようにする
  .github/workflows/create-release.yml
Labels: Build / CI

#2586 fix: paper を spigot 呼びしているのを直す
  .gitignore
  compose.yml
  docker/bungeecord/serverfiles/config.yml
  docker/paper/Dockerfile
  docker/paper/spigot.yml
  docker/paper/update-seichiassist.sh
Labels: development

#2584 hat コマンドで武器や防具がかぶれてしまう不具合を修正
  src/main/scala/com/github/unchama/seichiassist/commands/HatCommand.scala
Labels: bug

#2583 交換券をマインスタックに追加する
  src/main/scala/com/github/unchama/seichiassist/items/ExchangeTicket.scala
  src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
  src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/BukkitMineStackObjectList.scala
Labels: feature

#2579 直列設置スキル使用時に、メインハンドに持っているアイテムがブロックではない場合が考慮されていないのを修正
  src/main/scala/com/github/unchama/buildassist/listener/BlockLineUpTriggerListener.scala
Labels: bug

#2578 耐久が減ったアイテムもガチャ券に交換できるように
  src/main/scala/com/github/unchama/seichiassist/subsystems/tradesystems/subsystems/gachatrade/bukkit/listeners/GachaTradeListener.scala
  src/main/scala/com/github/unchama/seichiassist/subsystems/tradesystems/subsystems/gachatrade/bukkit/traderules/BukkitTrade.scala
Labels: improvement

#2577 二つ名メニューが動かないのを直す
  src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
  src/main/scala/com/github/unchama/seichiassist/data/MenuInventoryData.java
  src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
  src/main/scala/com/github/unchama/seichiassist/listener/invlistener/OnClickTitleMenu.scala
  src/main/scala/com/github/unchama/seichiassist/menus/TopLevelRouter.scala
  src/main/scala/com/github/unchama/seichiassist/menus/nicknames/NickNameMenu.scala
  src/main/scala/com/github/unchama/seichiassist/menus/nicknames/NicknameCombinationMenu.scala
  src/main/scala/com/github/unchama/seichiassist/menus/nicknames/NicknameShopMenu.scala
Labels: bug

#2574 docs: CONTRIBUTING.md の内容を整理し、読みやすくする
  CONTRIBUTING.md
Labels: development

#2593 feat: 現在有効なガチャリストを表示するコマンドを追加
  src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
Labels: feature

#2613 chore: 不具合報告の Issue Template を整備する
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
Labels: development

#2610 二つ名メニューが動かないのを直す
  src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
  src/main/scala/com/github/unchama/seichiassist/data/MenuInventoryData.java
  src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
  src/main/scala/com/github/unchama/seichiassist/listener/invlistener/OnClickTitleMenu.scala
  src/main/scala/com/github/unchama/seichiassist/menus/TopLevelRouter.scala
  src/main/scala/com/github/unchama/seichiassist/menus/nicknames/NickNameMenu.scala
  src/main/scala/com/github/unchama/seichiassist/menus/nicknames/NicknameCombinationMenu.scala
  src/main/scala/com/github/unchama/seichiassist/menus/nicknames/NicknameShopMenu.scala
  src/main/scala/com/github/unchama/seichiassist/menus/paging/PageCounter.scala
Labels: bug
